@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class AddtCommandParser
Class DeltCommandParser
Class DonetCommandParser
Class ReportCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> AddtCommandParser: <<create>>
AddressBookParser .down.> DeltCommandParser: <<create>>
AddressBookParser .down.> DonetCommandParser: <<create>>
AddressBookParser .down.> ReportCommandParser: <<create>>

AddtCommandParser ..> XYZCommand : <<create>>
DeltCommandParser ..> XYZCommand : <<create>>
DonetCommandParser ..> XYZCommand : <<create>>
ReportCommandParser ..> XYZCommand : <<create>>

AddressBookParser ..> Command : <<use>>

AddtCommandParser .up.|> Parser
DeltCommandParser .up.|> Parser
DonetCommandParser .up.|> Parser
ReportCommandParser .up.|> Parser

AddtCommandParser ..> ArgumentMultimap
DeltCommandParser ..> ArgumentMultimap
DonetCommandParser ..> ArgumentMultimap
ReportCommandParser ..> ArgumentMultimap

AddtCommandParser ..> ArgumentTokenizer
DeltCommandParser ..> ArgumentTokenizer
DonetCommandParser ..> ArgumentTokenizer
ReportCommandParser ..> ArgumentTokenizer

ArgumentTokenizer .left.> ArgumentMultimap

AddtCommandParser ..> CliSyntax
DeltCommandParser ..> CliSyntax
DonetCommandParser ..> CliSyntax
ReportCommandParser ..> CliSyntax

CliSyntax ..> Prefix

AddtCommandParser ..> ParserUtil
DeltCommandParser ..> ParserUtil
DonetCommandParser ..> ParserUtil
ReportCommandParser ..> ParserUtil

ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
@enduml
